---

image:
  repository: traefik
  tag: v3.3.3
  pullPolicy: IfNotPresent
 
deployment:
  enabled: true
  kind: Deployment
  replicas: 1
  healthcheckScheme: HTTP
  readinessPath: /ping
  livenessPath: /ping
  hostAliases:
  - ip: "127.0.0.1" # this is an example
    hostnames:
     - "gateway.virtual33.myguest.virtualbox.org"
                                        

globalArguments:
- "--global.checknewversion=false"
- "--global.sendanonymoususage=false"

logs:
  general:
    level: DEBUG
  access:
    enabled: false

providers:
  kubernetesCRD:
    enabled: true
  kubernetesIngress:
    enabled: true

ports:
  traefik:
    port: 8080
    protocol: TCP
    expose:
      default: false
    exposedPort: 8080
  web:
    port: 80
    protocol: TCP
    expose:
      default: true
    exposedPort: 80
    redirections:
      entryPoint:
        to: websecure
        scheme: https
        permanent: true
  websecure:
    port: 443
    protocol: TCP
    expose:
      default: true
    exposedPort: 443
    tls:
      enabled: true
      options: ""
      certResolver: ""
      domains:
        - main: "gateway.virtual33.myguest.virtualbox.org"
          sans:
            - "*.virtual33.myguest.virtualbox.org"
  ssh-netconf:
    port: 4334
    protocol: TCP
    expose:
      default: true
    exposedPort: 4334
  tls-netconf:
    port: 4335
    protocol: TCP
    expose:
      default: true
    exposedPort: 4335
 
serversTransport:
  insecureSkipVerify: true

api:
  insecure: true
  dashboard: true
  debug: true

readinessProbe:
  failureThreshold: 3
  initialDelaySeconds: 10
  timeoutSeconds: 5
  periodSeconds: 10

livenessProbe:
  failureThreshold: 3
  initialDelaySeconds: 10
  timeoutSeconds: 5
  periodSeconds: 10

ingressRoute:
  dashboard:
    enabled: true
    # Custom match rule with host domain
    matchRule: Host(`gateway.virtual33.myguest.virtualbox.org`)
    entryPoints: ["websecure"]
    # Add custom middlewares : authentication and redirection
    middlewares:
      - name: traefik-dashboard-auth
    services:
      - name: api@internal
        kind: TraefikService
  healthcheck:
    enabled: true
    matchRule: PathPrefix(`/ping`)
    services:
      - name: ping@internal
        kind: TraefikService
    entryPoints: ["traefik"]
    middlewares: []

extraObjects:
  # Basic Authentication Middleware
  - apiVersion: v1
    kind: Secret
    metadata:
      name: traefik-dashboard-auth-secret
    type: kubernetes.io/basic-auth
    stringData:
      username: admin
      password: changeme

  - apiVersion: traefik.io/v1alpha1
    kind: Middleware
    metadata:
      name: traefik-dashboard-auth
      namespace: traefik  # Ensure this matches your desired namespace
    spec:
      basicAuth:
        secret: traefik-dashboard-auth-secret

  # Strip Prefix Middleware
  - apiVersion: traefik.io/v1alpha1
    kind: Middleware
    metadata:
      name: strip
      namespace: traefik
    spec:
      stripPrefix:
        prefixes:
          - /traefik

