apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.name }}
  namespace: default
  labels:
    app: traefik
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: traefik
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args:
            {{- toYaml .Values.args | nindent 12 }}
          ports:
            - name: web
              containerPort: {{ .Values.ports.web }}
            - name: websecure
              containerPort: {{ .Values.ports.websecure }}
            - name: dashboard
              containerPort: {{ .Values.ports.dashboard }}
            - name: sshnetconf
              containerPort: {{ .Values.ports.sshNetconf }}
            - name: tlsnetconf
              containerPort: {{ .Values.ports.tlsNetconf }}

