apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.traefik.name }}-dashboard
  namespace: {{ .Values.traefik.namespace }}
spec:
  entryPoints:
    - websecure 
  routes:
    - match: Host(`gateway.virtual33.myguest.virtualbox.org`)
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
      middlewares:
        - name: default-headers

