apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: default
spec:
  type: NodePort
  ports:
    - name: web
      port: 80
      targetPort: {{ .Values.ports.web }}
      nodePort: {{ .Values.nodePorts.web }}
    - name: websecure
      port: 443
      targetPort: {{ .Values.ports.websecure }}
      nodePort: {{ .Values.nodePorts.websecure }}
    - name: dashboard
      port: 8080
      targetPort: {{ .Values.ports.dashboard }}
      nodePort: {{ .Values.nodePorts.dashboard }}
  selector:
    app: {{ .Release.Name }}

